!function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,function(t){return e[t]}.bind(null,o));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s="./src/js/main.js")}({"./src/js/_vars.js":
/*!*************************!*\
  !*** ./src/js/_vars.js ***!
  \*************************/
/*! exports provided: default */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\n/* harmony default export */ __webpack_exports__[\"default\"] = ({\n  $introSlider: document.querySelector('.home__slider'),\n  $mainSliderThumbs: document.querySelector('.home__slider-thumbs'),\n  $projectsFilter: document.querySelector('.projects__filter'),\n  $projectsItem: document.querySelectorAll('.projects__item'),\n  $projectsList: document.querySelector('.projects__list'),\n  $menuHeaderBurger: document.querySelector('.menu-header__burger'),\n  $menuHeaderNav: document.querySelector('.menu-header__nav'),\n  $headerTop: document.querySelector('.header__top')\n});\n\n//# sourceURL=webpack:///./src/js/_vars.js?")},"./src/js/components/portfolio-filter.js":
/*!***********************************************!*\
  !*** ./src/js/components/portfolio-filter.js ***!
  \***********************************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _vars__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../_vars */ \"./src/js/_vars.js\");\n\n\ntry {\n  var filterFunc = function filterFunc(e) {\n    if (e.target.classList.contains('projects__btn')) {\n      var catFilter = e.target.getAttribute('data-filter');\n\n      if (catFilter == 'all') {\n        if (!e.target.classList.contains('projects__btn--active')) {\n          this.querySelector('.projects__btn--active').classList.remove('projects__btn--active');\n          e.target.classList.add('projects__btn--active');\n          _vars__WEBPACK_IMPORTED_MODULE_0__[\"default\"].$projectsItem.forEach(function (item) {\n            item.classList.add('projects__hide-work');\n            setTimeout(function () {\n              item.classList.remove('projects__hide-work');\n              item.classList.add('projects__fade-in');\n            }, 20);\n          });\n        }\n      } else {\n        if (!e.target.classList.contains('projects__btn--active')) {\n          this.querySelector('.projects__btn--active').classList.remove('projects__btn--active');\n          e.target.classList.add('projects__btn--active');\n          _vars__WEBPACK_IMPORTED_MODULE_0__[\"default\"].$projectsItem.forEach(function (item) {\n            if (item.dataset.cat != catFilter) {\n              item.classList.add('projects__hide-work');\n              item.classList.remove('projects__btn--active');\n            } else {\n              item.classList.add('projects__hide-work');\n\n              if (item.classList.contains('projects__fade-in')) {\n                item.classList.remove('projects__fade-in');\n              }\n\n              setTimeout(function () {\n                item.classList.remove('projects__hide-work');\n                item.classList.add('projects__fade-in');\n              }, 20);\n            }\n          });\n        }\n      }\n    }\n  };\n\n  _vars__WEBPACK_IMPORTED_MODULE_0__[\"default\"].$projectsFilter.addEventListener('click', filterFunc, false);\n} catch (err) {}\n\n//# sourceURL=webpack:///./src/js/components/portfolio-filter.js?")},"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _components_portfolio_filter__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./components/portfolio-filter */ \"./src/js/components/portfolio-filter.js\");\n// import './_vars';\nvar navLink = document.querySelectorAll('.nav__link');\n\nif (document.location.pathname === '/index.html' || document.location.pathname === '/') {\n  navLink.forEach(function (item) {\n    if (item.pathname === '/index.html' || item.pathname === '/') {\n      item.classList.add('nav__link--active');\n    }\n  });\n} else if (document.location.pathname === '/blog.html') {\n  navLink.forEach(function (item) {\n    if (item.pathname === '/blog.html') {\n      item.classList.add('nav__link--active');\n    }\n  });\n} else if (document.location.pathname === '/portfolio.html') {\n  navLink.forEach(function (item) {\n    if (item.pathname === '/portfolio.html') {\n      item.classList.add('nav__link--active');\n    }\n  });\n} else if (document.location.pathname === '/contact.html') {\n  navLink.forEach(function (item) {\n    console.log(item.pathname);\n\n    if (item.pathname === '/contact.html') {\n      item.classList.add('nav__link--active');\n    }\n  });\n}\n\n; // import './components/main-slider';\n\n\n\n//# sourceURL=webpack:///./src/js/main.js?")}});
//# sourceMappingURL=main.js.map
